import pprint
import time
import json
import psycopg2
import SECRETS



try:
    connection_string = []
    connection_string.append("host=rhetoracle-db-instance.c2vrlkt9v1tp.us-west-2.rds.amazonaws.com")
    connection_string.append("dbname=rhetorical-db")
    connection_string.append("user=" + SECRETS['DB_USERNAME'])
    connection_string.append("password=" + SECRETS['DB_PASSWORD'])
    return psycopg2.connect(" ".join(connection_string))
except Exception as x:
    print "Error connecting to DB: ", x.args

con = connect_db()
cur = con.cursor()


def write_entry(sql):
    cur.execute(sql)

tweet_id = '123456'
text = "Hey man this is a message"
hashtags = "[hashtag1, hashtag2]"
user_mentions = "[user-mention]"
created_at = "Tuesday"
screen_name = 'FatTony'
url = 'http://www.website.com'
location = '[44, 55]'
in_reply_to_screen_name = 'pokerface'
retweets = 99

PUSH_SQL = """
INSERT INTO massive(
    tweet_id, text, hashtags, user_mentions,
    created_at, screen_name, url, location,
    inreplytostatusif, retweetcount)

VALUES(
    %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s); """(tweet_id, text, hashtags, user_mentions, created_at,
                             screen_name, url, location, in_reply_to_screen_name, retweets)

try:
    write_entry(PUSH_SQL)
except psycopg2.Error as x:
    # this will catch any errors generated by the database
    print "Oops there was a DB error!", x.args
